### ISSUE TITLE
哥，能增加一个 计时功能吗？

### ISSUE THREAD

**Issue by sunkeinfo** [Yuzuki616/AWS-Panel#18]
每台EC2 启动时候开始计时 ， 删除的时候统计这台机器运行了多少时间。并记录在案 。
可以查询哪一个时间段，所有机器一共运行了多长时间。例如本月所有机器包括已删除了机器一共跑了几个小时。这样。

哥您的联系方式是？
我企鹅 1002194531

**Comment by Yuzuki616** [comment]
aws提供了实例创建时间，日后将会支持显示创建时间
